version: '3'
services:
  web:
    image: mediawiki
    ports:
      - 8888:80
    links:
      - db
    volumes:
      - ./:/var/www/:cached
  db:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      # @see https://github.com/wikimedia/mediawiki/blob/master/includes/DefaultSettings.php
      MYSQL_DATABASE: 'my_wiki'
      MYSQL_USER: 'wikiuser'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - database:/var/lib/mysql
  # cache:
  #   image: memcached
  smtp:
    image: sj26/mailcatcher
    ports:
      - 1080:1080
volumes:
  database:
